package com.github.petruki.switcher.client.utils;

/**
 * Contains required and optionals key to setup the context
 * 
 * @author rogerio
 * @since 2019-12-24
 */
public interface SwitcherContextParam {
	
	/**
	 *  (String) Switcher API URL.
	 */
	String URL = "url";
	
	/**
	 * (String) API Key generated by your domain.
	 */
	String APIKEY = "apikey";
	
	/**
	 * (String) Registered domain name.
	 */
	String DOMAIN = "domain";
	
	/**
	 * (String) Name of this application. This value is used to track which applications are using switchers.
	 */
	String COMPONENT = "component";
	
	/**
	 * (String) Name of the environment where this application is running ('default' is a production environment).
	 */
	String ENVIRONMENT = "environment";
	
	/**
	 * (String) Complete path of the snapshot file, including the name of the file.
	 */
	String SNAPSHOT_LOCATION = "snapshotLocation";
	
	/**
	 * (boolean) Activate silent mode when the Switcher API is become offline.
	 */
	String SILENT_MODE = "silentMode";
	
	/**
	 * (String) Time that this client will retry to reach the online Switcher API after using the silent mode.
	 */
	String RETRY_AFTER = "retryAfter";
	
}
