package com.github.petruki.switcher.client.utils;

/**
 * Contains required and optional keys to set up the context
 * 
 * @author rogerio
 * @since 2019-12-24
 */
public interface SwitcherContextParam {
	
	/**
	 *  (String) Switcher API URL.
	 */
	String URL = "url";
	
	/**
	 * (String) API Key generated by your domain.
	 */
	String APIKEY = "apikey";
	
	/**
	 * (String) Registered domain name.
	 */
	String DOMAIN = "domain";
	
	/**
	 * (String) Name of this application. This value is used to track which applications are using switchers.
	 */
	String COMPONENT = "component";
	
	/**
	 * (String) Name of the environment where this application is running ('default' is a production environment).
	 */
	String ENVIRONMENT = "environment";
	
	/**
	 * (String) The absolute path of the snapshot file, including the file's name.
	 */
	String SNAPSHOT_FILE = "snapshotFile";
	
	/**
	 * (String) Folder path where all snapshot files are located.
	 */
	String SNAPSHOT_LOCATION = "snapshotLocation";
	
	/**
	 * (boolean) Activate snapshot autoload which will try to retrieve the snapshot from the API if the file does not exist.
	 */
	String SNAPSHOT_AUTO_LOAD = "snapshotAutoLoad";
	
	/**
	 * (boolean) Activate silent mode when the Switcher API becomes offline.
	 */
	String SILENT_MODE = "silentMode";
	
	/**
	 * (String) Time given to the library retry reaching the online Switcher API after using the silent mode.
	 */
	String RETRY_AFTER = "retryAfter";
	
}
