name: Master CI v2

on:
  push:
    branches: [ master-2 ]
  pull_request:
    branches: [ master-2 ]

jobs:
  build-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build/Test & SonarCloud Scan
        run: mvn -B clean verify -Pcoverage,sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-test:
    name: Build & Test - JDK ${{ matrix.Java }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17', '18']
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Show Versions
        run: mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2

      - name: Build/Test
        run: mvn -B clean package ${{ matrix.jdk }}
