name: Master CI v2

on:
  push:
    branches: [ master-2 ]
  pull_request:
    branches: [ master-2 ]

jobs:
  build-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build/Test & SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: env.SONAR_TOKEN != ''
        run: mvn -B clean verify -Pcoverage,sonar -Dsonar.token=$SONAR_TOKEN

  build-test:
    name: Build & Test - JDK ${{ matrix.java }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21', '25']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Show Versions
        run: mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ matrix.java }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build/Test
        run: mvn -B clean package
