name: Staging CI
run-name: Staging - Java ${{ github.event.inputs.jdk }} / ${{ github.event.inputs.os }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      jdk:
        description: 'JDK version'
        required: true
        default: '17'
      os:
        description: 'Operating System (ubuntu-20.04, ubuntu-latest, windows-latest)'
        required: true
        default: 'ubuntu-latest'

jobs:
  build-test:
    name: Build & Test - JDK ${{ github.event.inputs.jdk }} on ${{ github.event.inputs.os }}

    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ github.event.inputs.jdk }}

      - name: Show Versions
        run: mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2

      - name: Build/Test
        run: mvn -B clean package